### ISSUE TITLE
Projet Java

### ISSUE THREAD

**Issue by nfrankel** [di1606/monProjet#1]
Bonjour,

J'avais demandé d'utiliser Git avec un projet Java existant. Une classe Java ne correspond pas à ma demande. Merci de bien vouloir corriger.

**Comment by chococrypto** [comment]
@nfrankel, j'ai corrigé.

**Comment by nfrankel** [comment]
Je vous invite à fermer l'issue en référençant le commit dans le commentaire de clôture.
